# Funding Configuration
# Support the Pixielity Framework development

github: [pixielity]
# patreon: pixielity
# open_collective: pixielity
# ko_fi: pixielity
# custom: ['https://pixielity.com/sponsor']
